//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietGiaoDich
    {
        public int ID { get; set; }
        public string IDSanPham { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
