//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int ID { get; set; }
        public Nullable<int> MaLoaiSanPham { get; set; }
        public string Name { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string LinkHinhAnh { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
        public string ChatLuong { get; set; }
        public string MoTa { get; set; }
    }
}
